// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using QuickType;
//
//    var saveState = SaveState.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class SaveState
    {
        [JsonPropertyName("GameState")]
        public GameSaveState GameSaveState { get; set; }
    }

    public partial class GameSaveState
    {
        [JsonPropertyName("CurrentTurn")]
        public string CurrentTurn { get; set; }

        [JsonPropertyName("TurnNumber")]
        public int TurnNumber { get; set; }

        [JsonPropertyName("Pieces")]
        public List<SavedPiece> Pieces { get; set; }

        [JsonPropertyName("Graveyard")]
        public List<SavedGraveyard> Graveyard { get; set; }

        [JsonPropertyName("Board")]
        public SavedBoard SavedBoard { get; set; }

        [JsonPropertyName("Players")]
        public List<SavedPlayer> Players { get; set; }
    }

    public partial class SavedBoard
    {
        [JsonPropertyName("BoardShape")]
        public SavedVector BoardShape { get; set; }

        [JsonPropertyName("MaskedSquares")]
        public List<SavedVector> MaskedSquares { get; set; }
    }

    public partial class SavedVector
    {
        [JsonPropertyName("X")]
        public int X { get; set; }

        [JsonPropertyName("Y")]
        public int Y { get; set; }
    }

    public partial class SavedGraveyard
    {
        [JsonPropertyName("Pieces")]
        public List<SavedPiece> Pieces { get; set; }
    }

    public partial class SavedPiece
    {
        [JsonPropertyName("Type")]
        public string Type { get; set; }

        [JsonPropertyName("Color")]
        public string Color { get; set; }

        [JsonPropertyName("Owner")]
        public string Owner { get; set; }

        [JsonPropertyName("Rotation")]
        public int Rotation { get; set; }

        [JsonPropertyName("HasMoved")]
        public bool HasMoved { get; set; }

        [JsonPropertyName("GridPos")]
        public SavedVector GridPos { get; set; }

        [JsonPropertyName("MoveSet")]
        public SavedMoveSet SavedMoveSet { get; set; }
    }

    public partial class SavedMoveSet
    {
        [JsonPropertyName("LoadMoveSet")]
        public string LoadMoveSet { get; set; }

        [JsonPropertyName("Moves")]
        public List<SavedMove> Moves { get; set; }
    }

    public partial class SavedMove
    {
        [JsonPropertyName("Direction")]
        public SavedVector Direction { get; set; }

        [JsonPropertyName("Range")]
        public int Range { get; set; }

        [JsonPropertyName("Chain")]
        public SavedChain SavedChain { get; set; }

        [JsonPropertyName("Attributes")]
        public List<string> Attributes { get; set; }
    }

    public partial class SavedChain
    {
        [JsonPropertyName("ChainNumber")]
        public int ChainNumber { get; set; }

        [JsonPropertyName("ChainPos")]
        public int ChainPos { get; set; }
    }

    public partial class SavedPlayer
    {
        [JsonPropertyName("Color")]
        public string Color { get; set; }

        [JsonPropertyName("Name")]
        public string Name { get; set; }

        [JsonPropertyName("Controller")]
        public string Controller { get; set; }
    }

    public partial class SaveState
    {
        public static SaveState FromJson(string json) => JsonSerializer.Deserialize<SaveState>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this SaveState self) => JsonSerializer.Serialize(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }
    
    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
