global using Godot;
global using RogueGambit.Static.Constants;
global using RogueGambit.Models.State;
global using RogueGambit.Models;
global using System.Collections.Generic;
global using System.Linq;
global using System;
global using RogueGambit.Logic.Interfaces;
global using static RogueGambit.Static.Constants.GameConstants.PlayerStatus;
global using static RogueGambit.Static.Constants.PieceConstants;
global using static RogueGambit.Static.Constants.BoardConstants;
global using static RogueGambit.Static.Constants.PathConstants;
global using static RogueGambit.Static.Constants.FenMap;
global using static RogueGambit.Static.Constants.GameConstants;
global using static RogueGambit.DependencyInjector;
global using static RogueGambit.ServiceLocator;